// Code generated by "stringer -type Category"; DO NOT EDIT.

package tplimplv2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CategoryLayout-0]
	_ = x[CategoryBaseof-1]
	_ = x[CategoryMarkup-2]
	_ = x[CategoryShortcode-3]
	_ = x[CategoryPartial-4]
	_ = x[CategoryTemplates-5]
	_ = x[CategoryServer-6]
	_ = x[CategoryHugo-7]
}

const _Category_name = "CategoryLayoutCategoryBaseofCategoryMarkupCategoryShortcodeCategoryPartialCategoryTemplatesCategoryServerCategoryHugo"

var _Category_index = [...]uint8{0, 14, 28, 42, 59, 74, 91, 105, 117}

func (i Category) String() string {
	if i < 0 || i >= Category(len(_Category_index)-1) {
		return "Category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Category_name[_Category_index[i]:_Category_index[i+1]]
}
